In [23]:
import pandas as pd

In [24]:
df = pd.read_csv("../backend/data/raw/Customer_financial_profiles.csv")
df.head()

,id,current_age,birth_year,birth_month,gender,address,per_capita_income,yearly_income,total_debt,credit_score,...,transaction_id,date,client_id,card_id,amount,use_chip,merchant_id,merchant_city,merchant_state,zip
0,1,64,1961,3,Female,"Street 286, Indore, Madhya Pradesh - 452645",86125,1033501,280435,715,...,1251,2024-03-28,CLTIND00104,CRD001042,1483.94,Yes,MCH00496,Mumbai,Maharashtra,452645
1,2,39,1986,12,Female,"Street 268, Kolkata, West Bengal - 700555",68414,820965,0,834,...,9976,2025-09-20,CLTIND00213,CRD002132,1274.72,Yes,MCH00374,Mumbai,Maharashtra,700555
2,3,50,1975,7,Female,"Street 262, Lucknow, Uttar Pradesh - 226797",22595,271138,0,609,...,6084,2024-10-02,CLTIND03292,CRD032922,7622.04,No,MCH00108,Kolkata,West Bengal,226797
3,4,27,1998,2,Male,"Street 265, Nagpur, Maharashtra - 440623",24158,289898,0,782,...,3350,2023-09-02,CLTIND05205,CRD052053,3970.48,Yes,MCH00001,Indore,Madhya Pradesh,440623
4,5,45,1980,7,Other,"Street 157, Delhi, Delhi - 110965",45475,545697,117821,608,...,11725,2025-05-25,CLTIND04910,CRD049101,418.45,No,MCH00254,Bengaluru,Karnataka,110965

In [25]:
# (df["yearly_income"] == 0).sum()
df["debt_to_income"] = df["total_debt"] / df["yearly_income"]
df[["total_debt", "yearly_income", "debt_to_income"]].head()

   total_debt  yearly_income  debt_to_income
0      280435        1033501        0.271345
1           0         820965        0.000000
2           0         271138        0.000000
3           0         289898        0.000000
4      117821         545697        0.215909

In [26]:
df["default_risk"] = ((df["credit_score"]<600) & (df["debt_to_income"]>0.5)).astype(int)
df[["credit_score", "debt_to_income", "default_risk"]].head()

   credit_score  debt_to_income  default_risk
0           715        0.271345             0
1           834        0.000000             0
2           609        0.000000             0
3           782        0.000000             0
4           608        0.215909             0

In [27]:
print(df["gender"].unique())


df = pd.get_dummies(
    df,
    columns=["gender"],
    dtype=int
)

['Female' 'Male' 'Other']

In [31]:
print(df.filter(regex="gender").columns.tolist())

['gender_Female', 'gender_Male', 'gender_Other']

In [37]:
columns_to_drop = [
    "id",
    "birth_year",
    "birth_month",
    "transaction_id",
    "date",
    "client_id",
    "card_id",
    "merchant_id",
    "merchant_city",
    "merchant_state",
    "address",
    "zip"
]
df = df.drop(columns=columns_to_drop, errors="ignore")
print(df.columns.tolist())

['current_age', 'per_capita_income', 'yearly_income', 'total_debt', 'credit_score', 'num_credit_cards', 'amount', 'use_chip', 'debt_to_income', 'default_risk', 'gender_Female', 'gender_Male', 'gender_Other']

In [38]:
df.to_csv("../backend/data/processed/processed_data.csv", index=False)
print("Processed dataset saved successfully!")

Processed dataset saved successfully!