In [23]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from xgboost import XGBClassifier

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    classification_report
)

import joblib

In [24]:
df = pd.read_csv("../backend/data/processed/processed_data.csv")
df.head()

,current_age,per_capita_income,yearly_income,total_debt,credit_score,num_credit_cards,amount,use_chip,debt_to_income,default_risk,gender_Female,gender_Male,gender_Other
0,64,86125,1033501,280435,715,5,1483.94,Yes,0.271345,0,1,0,0
1,39,68414,820965,0,834,3,1274.72,Yes,0.000000,0,1,0,0
2,50,22595,271138,0,609,2,7622.04,No,0.000000,0,1,0,0
3,27,24158,289898,0,782,3,3970.48,Yes,0.000000,0,0,1,0
4,45,45475,545697,117821,608,2,418.45,No,0.215909,0,0,0,1

In [25]:
print("Data Type:", df["use_chip"].dtype)
print("Unique Values:", df["use_chip"].unique())

Data Type: object
Unique Values: ['Yes' 'No']

In [26]:
df["use_chip"] = df["use_chip"].map({"No": 0, "Yes": 1})

print(df["use_chip"].unique())
df[["use_chip"]].head()

[1 0]

   use_chip
0         1
1         1
2         0
3         1
4         0

In [27]:
x = df.drop(columns=["default_risk", "credit_score", "debt_to_income"])
y = df["default_risk"]
print("Features Shape:", x.shape)
print("Target Shape:", y.shape)

Features Shape: (20000, 10)
Target Shape: (20000,)

In [28]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)
print("X_train:", x_train.shape)
print("X_test :", x_test.shape)
print("y_train:", y_train.shape)
print("y_test :", y_test.shape)

X_train: (16000, 10)
X_test : (4000, 10)
y_train: (16000,)
y_test : (4000,)

In [29]:
log_model = LogisticRegression(max_iter=1000, random_state=42)
log_model.fit(x_train, y_train)
print("Logistic Regression model trained successfully!")

Logistic Regression model trained successfully!

In [30]:
xgb_model = XGBClassifier(random_state=42, eval_metric="logloss")
xgb_model.fit(x_train, y_train)
print("XGBoost model trained successfully!")

XGBoost model trained successfully!

In [31]:
log_predictions = log_model.predict(x_test)
xgb_predictions = xgb_model.predict(x_test)

In [32]:
print("========== Logistic Regression ==========")

print("Accuracy :", accuracy_score(y_test, log_predictions))
print("Precision:", precision_score(y_test, log_predictions))
print("Recall   :", recall_score(y_test, log_predictions))
print("F1 Score :", f1_score(y_test, log_predictions))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, log_predictions))

print("\nClassification Report:")
print(classification_report(y_test, log_predictions))


print("\n========== XGBoost ==========")

print("Accuracy :", accuracy_score(y_test, xgb_predictions))
print("Precision:", precision_score(y_test, xgb_predictions))
print("Recall   :", recall_score(y_test, xgb_predictions))
print("F1 Score :", f1_score(y_test, xgb_predictions))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, xgb_predictions))

print("\nClassification Report:")
print(classification_report(y_test, xgb_predictions))

========== Logistic Regression ==========
Accuracy : 0.98575
Precision: 0.14285714285714285
Recall   : 0.0425531914893617
F1 Score : 0.06557377049180328

Confusion Matrix:
[[3941   12]
 [  45    2]]

Classification Report:
              precision    recall  f1-score   support

           0       0.99      1.00      0.99      3953
           1       0.14      0.04      0.07        47

    accuracy                           0.99      4000
   macro avg       0.57      0.52      0.53      4000
weighted avg       0.98      0.99      0.98      4000


========== XGBoost ==========
Accuracy : 0.9975
Precision: 0.9512195121951219
Recall   : 0.8297872340425532
F1 Score : 0.8863636363636364

Confusion Matrix:
[[3951    2]
 [   8   39]]

Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00      3953
           1       0.95      0.83      0.89        47

    accuracy                           1.00      4000
   macro avg       0.97      0.91      0.94      4000
weighted avg       1.00      1.00      1.00      4000

In [33]:
joblib.dump(xgb_model, "../backend/models/xgboost_model.pkl")
print("XGBoost model saved successfully!")

XGBoost model saved successfully!